[package]
name = "graphics"
version = "0.1.0"
authors = ["Jakob <jakobfischer93@gmail.com>"]
edition = "2018"

[dependencies]
utility = { path = "../utility" }

gl = "0.11"
glutin = "0.19"
glm = "0.2"
log = "0.4"
image = "0.20"
num-traits = "0.2"
