[package]
name = "utility"
version = "0.1.0"
authors = ["Jakob <jakobfischer93@gmail.com>"]
edition = "2018"

[dependencies]
glm = "0.2"
gl = "0.11"
log = "0.4"
num-traits = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
